/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': '#002e5a',
        'primary-container': '#004481',
        'on-primary': '#ffffff',
        'on-primary-container': '#85b3f7',
        'primary-fixed': '#d5e3ff',
        'primary-fixed-dim': '#a6c8ff',
        'on-primary-fixed': '#001c3b',
        'on-primary-fixed-variant': '#074784',
        'secondary': '#48626e',
        'secondary-container': '#cbe7f5',
        'secondary-fixed': '#cbe7f5',
        'secondary-fixed-dim': '#afcbd8',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#4e6874',
        'on-secondary-fixed': '#021f29',
        'on-secondary-fixed-variant': '#304a55',
        'tertiary': '#630010',
        'tertiary-container': '#8d001b',
        'tertiary-fixed': '#ffdad8',
        'tertiary-fixed-dim': '#ffb3b1',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#ff9291',
        'on-tertiary-fixed': '#410007',
        'on-tertiary-fixed-variant': '#92001c',
        'surface': '#f7fafc',
        'surface-dim': '#d7dadc',
        'surface-bright': '#f7fafc',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f1f4f6',
        'surface-container': '#ebeef0',
        'surface-container-high': '#e5e9eb',
        'surface-container-highest': '#e0e3e5',
        'surface-tint': '#2d5f9e',
        'surface-variant': '#e0e3e5',
        'on-surface': '#181c1e',
        'on-surface-variant': '#424750',
        'on-background': '#181c1e',
        'background': '#f7fafc',
        'outline': '#737781',
        'outline-variant': '#c2c6d2',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eef1f3',
        'inverse-primary': '#a6c8ff',
      },
      fontFamily: {
        headline: ['"Public Sans Variable"', '"Public Sans"', 'sans-serif'],
        body: ['"Newsreader Variable"', 'Newsreader', 'serif'],
        label: ['"Public Sans Variable"', '"Public Sans"', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
}
